# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json


site_name: Sentiment analysis in Twitter for the Medellin Development Plan

nav:
    - Home: index.md
    
    
theme:
  name: material
