# -*- coding: utf-8 -*-
"""
This file contains all the extra code that we need to develop the sentimet analysis of the
tweets in spanish made about Medellin between 2019-2022
"""

replace_punctuation_dict = { '¿':'','?':'','!':'','¡':'','"':'','(':'',')':'','/':'','*':'',',':'','.':'','-':'','*':'',
                            ':':'','…':'','#':'','@':'',"'":"",'|':'','“':'','”':'','%':'','&':'','_':''}

replace_accent_dict ={'á':'a','é':'e','í':'i','ó':'o','ú':'u','ü':'u'}

replace_numbers_dict = {'1':'','2':'','3':'','4':'','5':'','6':'','7':'','8':'','9':'','0':''}

replace_key_word = {
    'cultura':1,'empresa':2,'jovenes':3,'metro':4,'movilidad':5,'seguridad':6,'tecnologia':7,'trabajo':8,'vida':9
}

stop_words = ['de','la','en','y','el','que','a','medellin','los','con','no','por','es','para','del','se',
              'un','las','una','lo','su','mas','esta','como','si','le','este','al','me','mi','pero','o',
              'sus','hay','son','nos','ya','te','tiene','hoy','todo','sin','tu','ha','q','fue','eso',
              'todos','muy','años','ser','porque','asi','cuando','solo','desde','hace','les','ni','yo',
              'hacer','estan','donde','dia','ese','entre','hasta','toda','esa','e','va','han','aqui','parte',
              'esto','tan','ahora','uno','bien','cada','quien','tienen','mucho','gran','tambien','estamos',
              'usted','puede','sera','dos','ver','nuestro','siempre','estos','contra','nada','dias','era',
              'tener','debe','a','traves','sobre','sea','vez','cali','menos','muchos','sido','tenemos','san',
              'año','durante','ejemplo','medio','soy','buen','señor','cuenta','hola','aca','van','estas',
              'algo','mismo','da','nunca','todas','hecho','hizo','he','vamos','d','estoy','paso','cual','bogota',
              'nuestro','nuestra','antioquia','colombia','nuestros','secretaria','in','km','ft','ir','vs']

model_stop_wprds = ['de','la','en','y','el','que','a', 'los','con','no','por','es','para','del','se',
              'un','las','una','lo','su','como','si','le','este','al','me','mi','pero','o',
              'sus','hay','son','nos','ya','te','hoy','todo','sin','tu','ha','q','fue','eso',
              'todos','muy','años','ser','porque','asi','cuando','solo','desde','hace','les','ni','yo',
              'estan','donde','dia','ese','entre','hasta','toda','esa','e','va','han','aqui','parte',
              'esto','tan','ahora','uno','cada','quien','tambien','estamos',
              'usted','sera','dos','ver','nuestro','siempre','estos','dias','era',
              'debe','a','traves','sobre','sea','vez','cali','muchos','sido','san',
              'año','durante','ejemplo','medio','soy','señor','cuenta','hola','aca','van','estas',
              'algo','mismo','da','nunca','todas','hecho','hizo','he','vamos','d','estoy','paso','cual','bogota',
              'nuestro','nuestra','colombia','nuestros','secretaria','in','km','ft','ir','vs']

negation_words = ['no','mal','caos','falta']

word_rating_s ={
    "abandonados": -3, "abandono": -3, "abismo": -1, "aburrida": -2, "abusar": -3, "abuso": -3,
    "abusos": -3, "acabar":-1, "acierto":1, "admiro":1, "agradece": 2, "agradecen": 2, 
    "agradecido": 2, "agradezco": 2,
    "alegria": 3, "alias":-1 , "amenazar": -3, "amenazaron": -3, "aportan": 2, "aprecia": 1, 
    "arrogancia": -2,
    "arrogante": -2, "arruino": -3, "arruinando": -3, "asco": -3, "asesinar": -3, "asesinaron": -3, 
    "asesinatos": -1,
    "asesino": -3, "atento": 1, "atracar": -2, "atropellos": -2, "avanzamos": 1, "avanzar": 1,
    "ayudan": 1, "baboso": -1, "bajar": -1, "bandido": -2, "bandidos": -2, "bloquean": -1,
    "bloqueando": -1, "buena": 2, "caido": -1, "calificado": 1, "cancelado": -1, "caos": -2,
    "capturan": 1, "capturaron": 1, "celebracion": 1, "celebrando": 2, "clientelista":-2, "cochino": -2, 
    "cochinada": -2, "comunismo": -1, "comunista": -1, "contradictorio":-1,
    "construir": 2, "construya": 2, "construye": 2, "construyendo": 2, "correcta": 2, "corrupcion": -2,
    "corrupta": -2, "corruptas": -2, "corrupto": -2, "corruptos": -2, "costosas": 1, "creando": 2,
    "crear": 2, "creativo": 1, "crecer":2, "creido": -1, "criminal": -2, "criminales": -2, 
    "critican": -1, "criticar": -1,
    "cuidar": 1, "culpa": -1, "cumplieron": 2, "dañando": -2, "dañar": -2, "dañen": -2,
    "daño": -2, "defender": 1, "delincuencia": -2, "delincuente": -2, "delincuentes": -2, "desangrando": -3,
    "desastre": -3, "desastrosa": -3, "descarada": -2, "descarado": -2, "descuidar": -1, "descuido": -1,
    "desesperado": -2, "desestabilizar": -2, "desgracia": -1, "desigualdad": -1, "desplazamiento": -1, "despreciar": -2, 
    "desprecio": -1,
    "desprestigiar": -1, "destruccion": -1, "destruido": -1, "destruir": -2, "destruirlo": -2, "destruyan": -2,
    "destruye": -2, "destruyen": -2, "destruyendo": -3, "destruyeron": -2, "destruyo": -2, "discriminacion": -1,
    "disfrutando": 1, "dolor": -2, "dudas": -1, "dudo": -1, "echaron":-1, "eficiente": 1, 
    "emergencia": -2, "emocion": 2,
    "emocionada": 2, "encantan": 3, "enemigo": -1, "engaño": -2, "equivocacion": -1, "equivocar": -1,
    "equivoque": -1, "error": -1, "errores": -1, "escandalo": -2, "escandalos": -2, "estupidez": -2,
    "estupido": -2, "evitaron": 0, "excelencia": 2, "excelente": 2, "exitosa": 3, "exitoso":3,
    "expropiar": -2,
    "extorsion": -3, "fallo": -1, "falsa": -1, "falsas": -1, "fascista": -2, "felicitamos": 2,
    "fortalece": 2, "fracaso": -3, "fraude": -2, "funciona": 2, "ganan": 2, "gano": 2,
    "garantizamos": 2, "genocida": -3, "golpe": -1, "graves": -1, "gravisimo": -3, "gusta": 2,
    "hampon": -3, "hermoso": 2, "homofobia": -1, "honesta": 2, "honesto": 2, "honestos": 2,
    "honor": 2, "honrado": 2, "hostil": -1, "hpta": -3, "hurto": -1, "idiotas": -2,
    "ilegales": -2, "ilegalidad": -2, "ilegalmente": -2, "ilicito": -1, "impedir": -1, "impiden": -1,
    "importa": 2,
    "imponer": -1, "impulsar": 2, "impunidad": -1, "incautos": -1, "incompetente": -2, "ineficiencia": -1,
    "ineficiente": -1, "inepto": -2, "ineptos": -2, "innovador": 2, "innovadora": 2, "innovadoras": 2,
    "innovadores": 2, "instancia": 0, "insulto": -2, "inviable": -1, "irregularidades": -2, "irrespeto": -3,
    "irresponsable": -3, "izquierdista": -1, "jodiendo": -1, "jodio": -2, "lacra": -3, "ladron": -2,
    "logrado": 2, "logramos": 2, "lograron": 2, "mal": -1, "mala": -1, "malandro": -1,
    "malandros": -1, "malo": -1, "malos": -1, "mamados": -2, "mamerto": -1, "mamertos": -1,
    "matan": -3, "matar": -3, "mejor": 3, "mejoramiento": 2, "mejorar": 2, "mejores": 2,
    "mentira": -1, "mentiroso": -1, "mezquinos": -2, "miedo": -1, "mierda": -2, "miserable": -2,
    "modernizar": 2, "narcos":-1, "nefasta": -1, "nefasto": -1, "negar": -1, "negativo": -1, 
    "odia": -2,
    "odio": -2, "oportunismo": -1, "panico": -1, "peligroso": -2, "pendejo": -1, "pendejos": -1,
    "peor": -2, "perder": -1, "perdi": -1, "perdio": -1, "perjudicar": -2, "permitira": 1,
    "pesimo": -2, "petroñero": -1, "pierde": -1, "plaga": -2, "poca": 0, "podridas": -1,
    "politiqueros": -1, "preocupada": -1, "preocupante": -1, "problema": 0, "puede": 2 , "quebrar": -1, 
    "quebro": -1,
    "quemaron": -1, "quitar": -1, "rabia": -3, "reactivacion": 2, "rechazan": -1, "rechazo": -1,
    "reclamos": -1, "recuperacion": 2, "represion": -1, "resta": -1, "ridicula": -2, "ridiculo": -2,
    "riesgo": -1, "riesgos": -1, "roba": -2, "robado": -2, "roban": -2, "robando": -2,
    "robar": -2, "robaron": -2, "robarse": -2, "roben": -2, "robo": -2, "roto": -1,
    "sacoculo": -2, "satisfechos": 2, "sinverguenza": -1, "sinverguenzas": -1, "sirven": 2, "sobrecosto": -1,
    "sobrecostos": -1, "suerte": 1, "sufre": -2, "sufrido": -2, "sufriendo": -2, "sufrio": -2,
    "sufrir": -2, "superacion": 2, "susto": -1, "talento": 2, "talentos": 2, "talentosos": 2,
    "terrible": -2, "terribles": -2, "terrorismo": -3, "testaferro": -1, "tonto": -1, "torpeza":-1,
    "toxico": -1,
    "tragedia": -2, "trampa": -1, "triste": -1, "tristemente": -1, "tristeza": -1, "triunfo": 3,
    "uribestia":-2,
    "utiles": 2, "vandalos": -1, "venganza": -2, "verguenza": -1, "violan": -3, "violar": -3,
    "violentos": -1, "volcamiento": -1, "vulgar": -1
}

word_rating_g = {
    "abandonados": -1,
    "abandono": -1,
    "abismo": -1,
    "aburrida": -1,
    "abusar": -1,
    "abuso": -1,
    "abusos": -1,
    "acabar":-1,
    "acierto":1,
    "admiro":1,
    "agradece": 1,
    "agradecen": 1,
    "agradecido": 1,
    "agradezco": 1,
    "alegria": 1,
    "alias":-1,
    "amenazar": -1,
    "amenazaron": -1,
    "aportan": 1,
    "aprecia": 1,
    "arrogancia": -1,
    "arrogante": -1,
    "arruinando": -3,
    "arruino": -1,
    "asco": -1,
    "asesinar": -1,
    "asesinaron": -1,
    "asesinatos": -1,
    "asesino": -1,
    "atento": 1,
    "atracar": -1,
    "atropellos": -1,
    "avanzamos": 1,
    "avanzar": 1,
    "ayudan": 1,
    "baboso": -1,
    "bajar": -1,
    "bandido": -1,
    "bandidos": -1,
    "bloquean": -1,
    "bloqueando": -1,
    "buena": 1,
    "caido": -1,
    "calificado": 1,
    "cancelado": -1,
    "caos": -1,
    "capturan": 1,
    "capturaron": 1,
    "celebracion": 1,
    "celebrando": 1,
    "clientelista":-1,
    "cochinada": -1,
    "cochino":-1,
    "comunismo": -1,
    "comunista": -1,
    "construir": 1,
    "construya": 1,
    "construye": 1,
    "construyendo": 1,
    "contradictorio":-1,
    "correcta": 1,
    "corrupcion": -1,
    "corrupta": -1,
    "corruptas": -1,
    "corrupto": -1,
    "corruptos": -1,
    "costosas": 1,
    "creando": 1,
    "crear": 1,
    "creativo": 1,
    "crecer":1,
    "creido": -1,
    "criminal": -1,
    "criminales":-1,
    "critican": -1,
    "criticar": -1,
    "cuidar": 1,
    "culpa": -1,
    "cumplieron": 1,
    "dañando": -1,
    "dañar": -1,
    "dañen": -1,
    "daño": -1,
    "defender": 1,
    "delincuencia": -1,
    "delincuente": -1,
    "delincuentes": -1,
    "desangrando": -1,
    "desastre": -1,
    "desastrosa": -1,
    "descarada": -1,
    "descarado": -1,
    "descuidar": -1,
    "descuido": -1,
    "desesperado": -1,
    "desestabilizar": -1,
    "desgracia": -1,
    "desigualdad": -1,
    "desplazamiento": -1,
    "despreciar": -1,
    "desprecio": -1,
    "desprestigiar": -1,
    "destruccion": -1,
    "destruido": -1,
    "destruir": -1,
    "destruirlo": -1,
    "destruyan": -1,
    "destruye": -1,
    "destruyen": -1,
    "destruyendo": -1,
    "destruyeron": -1,
    "destruyo": -1,
    "discriminacion": -1,
    "disfrutando": 1,
    "dolor": -1,
    "dudas": -1,
    "dudo": -1,
    "echaron":-1,
    "eficiente": 1,
    "emergencia": -1,
    "emocion":1,
    "emocionada": 1,
    "encantan": 1,
    "enemigo": -1,
    "engaño": -1,
    "equivocacion": -1,
    "equivocar": -1,
    "equivoque": -1,
    "error": -1,
    "errores": -1,
    "escandalo": -1,
    "escandalos": -1,
    "estupidez": -1,
    "estupido": -1,
    "evitaron": 0,
    "excelencia": 1,
    "excelente": 1,
    "exitosa": 1,
    "exitoso":1,
    "expropiar": -1,
    "extorsion": -1,
    "fallo": -1,
    "falsa": -1,
    "falsas": -1,
    "fascista": -1,
    "felicitamos": 1,
    "fortalece": 1,
    "fracaso": -1,
    "fraude": -1,
    "funciona": 1,
    "ganan": 1,
    "gano": 1,
    "garantizamos": 1,
    "genocida": -1,
    "golpe": -1,
    "graves": -1,
    "gravisimo": -1,
    "gusta": 1,
    "hampon": -1,
    "hermoso": 1,
    "homofobia": -1,
    "honesta": 1,
    "honesto": 1,
    "honestos": 1,
    "honor": 1,
    "honrado": 1,
    "hostil": -1,
    "hpta": -1,
    "hurto": -1,
    "idiotas": -1,
    "ilegales": -1,
    "ilegalidad": -1,
    "ilegalmente": -1,
    "ilicito": -1,
    "impedir": -1,
    "impiden": -1,
    "imponer": -1,
    "importa":1,
    "impulsar": 1,
    "impunidad": -1,
    "incautos": -1,
    "incompetente": -1,
    "ineficiencia": -1,
    "ineficiente": -1,
    "inepto": -1,
    "ineptos": -1,
    "innovador": 1,
    "innovadora": 1,
    "innovadoras": 1,
    "innovadores": 1,
    "instancia": 0,
    "insulto": -1,
    "inviable": -1,
    "irregularidades": -1,
    "irrespeto": -1,
    "irresponsable": -1,
    "izquierdista": -1,
    "jodiendo": -1,
    "jodio": -1,
    "lacra": -1,
    "ladron": -1,
    "logrado": 1,
    "logramos": 1,
    "lograron": 1,
    "mal": -1,
    "mala": -1,
    "malandro": -1,
    "malandros": -1,
    "malo": -1,
    "malos": -1,
    "mamados": -1,
    "mamerto": -1,
    "mamertos": -1,
    "matan": -1,
    "matar": -1,
    "mejor": 1,
    "mejoramiento": 1,
    "mejorar": 1,
    "mejores": 1,
    "mentira": -1,
    "mentiroso": -1,
    "mezquinos": -1,
    "miedo": -1,
    "mierda": -1,
    "miserable": -1,
    "modernizar": 1,
    "narcos":-1,
    "nefasta": -1,
    "nefasto": -1,
    "negar": -1,
    "negativo": -1,
    "odia": -1,
    "odio": -1,
    "oportunismo": -1,
    "panico": -1,
    "peligroso": -1,
    "pendejo": -1,
    "pendejos": -1,
    "peor": -1,
    "perder": -1,
    "perdi": -1,
    "perdio": -1,
    "perjudicar": -1,
    "permitira": 1,
    "pesimo": -1,
    "petroñero": -1,
    "pierde": -1,
    "plaga": -1,
    "poca": 0,
    "podridas": -1,
    "politiqueros": -1,
    "preocupada": -1,
    "preocupante": -1,
    "problema": 0,
    "puede": 1,
    "quebrar": -1,
    "quebro": -1,
    "quemaron": -1,
    "quitar": -1,
    "rabia": -1,
    "reactivacion": 1,
    "rechazan": -1,
    "rechazo": -1,
    "reclamos": -1,
    "recuperacion": 1,
    "represion": -1,
    "resta": -1,
    "ridicula": -1,
    "ridiculo": -1,
    "riesgo": -1,
    "riesgos": -1,
    "roba": -1,
    "robado": -1,
    "roban": -1,
    "robando": -1,
    "robar": -1,
    "robaron": -1,
    "robarse": -1,
    "roben": -1,
    "robo": -1,
    "roto": -1,
    "sacoculo": -1,
    "satisfechos": 1,
    "sinverguenza": -1,
    "sinverguenzas": -1,
    "sirven": 1,
    "sobrecosto": -1,
    "sobrecostos": -1,
    "suerte": 1,
    "sufre": -1,
    "sufrido": -1,
    "sufriendo": -1,
    "sufrio": -1,
    "sufrir": -1,
    "superacion": 1,
    "susto": -1,
    "talento": 1,
    "talentos": 1,
    "talentosos": 1,
    "terrible": -1,
    "terribles": -1,
    "terrorismo": -1,
    "testaferro": -1,
    "tonto": -1,
    "torpeza":-1,
    "toxico": -1,
    "tragedia": -1,
    "trampa": -1,
    "triste": -1,
    "tristemente": -1,
    "tristeza": -1,
    "triunfo": 1,
    "uribestia":-1,
    "utiles": 1,
    "vandalos": -1,
    "venganza": -1,
    "verguenza": -1,
    "violan": -1,
    "violar": -1,
    "violentos": -1,
    "volcamiento": -1, 
    "vulgar": -1
}