# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json


site_name: Sentiment analysis in Twitter for the Medellin Development Plan

nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'Getting Started': 'user-guide/getting-started.md'   
    - Source Code:
        - 'Data': 'source-code/data.md'
        - 'Features': 'source-code/features.md'
        - 'Models': 'source-code/models.md'
        - 'Visualization': 'source-code/visualization.md'
    - Notebooks: 
        - 'Notebooks': 'notebooks/notebooks.md'
        - 'Exploratory': 'notebooks/exploratory.md'
        - 'Report': 'notebooks/report.md'
    - Models:
        - 'Models': 'models.md'
    - About:
        - 'License': 'about/license.md'
        - 'Release Notes': 'about/release-notes.md'
    
    
theme:
  icon:
    repo: fontawesome/brands/github
    
  name: material
  
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - header.autohide
  
  palette: 

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: cyan
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    
    
extra:
  alternate:
    - name: English
      link: /en/ 
      lang: en
    - name: Español
      link: /de/
      lang: es


repo_url: https://github.com/GDLPLearning/Sentiment-Analysis-for-the-MDP

repo_name: Sentiment-Analysis-for-the-MDP

edit_uri: ""

plugins:
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
      
  - search:
      lang: 
        - en
        - es
    
  