site_name: Sentiment Analysis in Twitter for the Medellin Development Plan

nav:
  - Index: 'index.md'
  - About: 'about.md'
  - License: 'license.md'
  - Getting started:
      - Introduction: 'introduction.md'
  - Authentication: 'authenticated.md'

theme: readthedocs
